### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by eson57** [condo4/carbudget#22]
Hi,
I have Swedish translation ready for you, if you want it. I just want to test translation first, but I can't find where to place the file? Normally there should be a "Translations" directory at *usr/share/app folder* but there is none.

**Comment by condo4** [comment]
Hi,

Thanks for your future contribution,
Today, I build translation with the application in a resource file (qm 
file).
In fact, today I have only 4 translations, and i was easy to do it.
In near future, it will be interesting to externalize this translation, 
but I don't do this job now.
You can test it by checkout the application, place your translation in 
the i18n folder, add the entry (TRANSLATIONS =)  in the .pro and add it 
into Ressources.qrc


Best regards,
Fabien Proriol

**Comment by eson57** [comment]
Thanks! I'll pull request.
