### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by condo4** [condo4/carbudget#24]
The types of 'stations' and 'fuel' types I enter in the current version of the app (0.10) in our Store, gets deleted after I update the app with the latest version (0.12). The loss of data is also inconsistent; which means sometimes all the stations and fuel types are gone after the update, and sometimes some of them gets deleted and some are still there.

I've experienced this behavior while testing your application against a device with SailfishOS version 1.1.6. To be more detailed, I used mostly long names for any of these entries; names with multiple words that have spaces between them.

This happened to me during normal usage of the app. I had created two different cost types and the type list was like:
0: Not set 
1: typeX 
2: typeY. 

After a while, I went to add a new cost, but then my previously created cost types were lost: I saw only the option 0: Not set. And when I went to create new cost types, they were saved as 3: and 4:, but still those first two options weren't visible.

**Comment by direc85** [comment]
I believe this has to do with lost database connection or file opening error during app usage. This has lead into data being in memory during app usage and apparently seem OK, but not getting saved. Can you still reproduce this with the latest version in GitHub? Can you send the problematic .cbg file?

**Comment by condo4** [comment]
Hi,
In fact this was a message leaved on harbour submit review; I transformed it in github issue.
I don't remember exactly, but I think I fixed this issue in 0.14.
I had no more information but, when I released the 0.14, the harbour tester didn't reproduce it...

**Comment by condo4** [comment]
Seen to be fixed
