### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by condo4** [condo4/carbudget#26]
I was able to crash your application in a way that the screen went almost black, not crashing or closed, but I was not able to use it any more. I was adding a new tank, I did not do anything special. This issue happened totally unexpectedly, so there are not any exact steps to reproduce, but I will add here the logs from that time, and you can go through them: 

hein? 23 10:54:28 Jolla lipstick[844]: [W] DeclarativeWindow::_setAllowedOrientations:241 - Invalid allowedOrientations value: 0
hein? 23 10:54:29 Jolla kernel: SLIM_CL: skip reconfig sequence
hein? 23 10:54:29 Jolla kernel: SLIM_CL: skip reconfig sequence
hein? 23 10:54:32 Jolla [3732]: [W] QSqlDatabasePrivate::addDatabase:261 - QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
hein? 23 10:54:32 Jolla [3732]: [D] Car::db_init:72 - DB: "/home/nemo/.local/share/harbour-carbudget/harbour-carbudget/Testi222.cbg" 
hein? 23 10:54:32 Jolla [3732]: [D] Car::Car:344 - Database version 4 
hein? 23 10:54:32 Jolla [3732]: [W] QSqlQuery::value:416 - QSqlQuery::value: not positioned on a valid record
hein? 23 10:54:32 Jolla [3732]: [D] Car::nbtire:1291 - Find nbtire in database: 0 
hein? 23 10:54:32 Jolla [3732]: [D] Car::nbtire:1295 - Default nbtire not set in database, set to 4 
hein? 23 10:54:32 Jolla [3732]: [W] QSqlQuery::value:416 - QSqlQuery::value: not positioned on a valid record
hein? 23 10:54:32 Jolla [3732]: [D] Car::buyingprice:1332 - Find buyingprice in database: 0 
hein? 23 10:54:32 Jolla [3732]: [D] Car::buyingprice:1336 - Buying price not set in database, set to 0 
hein? 23 10:54:32 Jolla [3732]: [W] QSqlQuery::value:416 - QSqlQuery::value: not positioned on a valid record
hein? 23 10:54:32 Jolla [3732]: [D] Car::sellingprice:1372 - Find sellingprice in database: 0 
hein? 23 10:54:32 Jolla [3732]: [D] Car::sellingprice:1376 - Selling price not set in database, set to 0 
hein? 23 10:54:32 Jolla [3732]: [W] QSqlQuery::value:416 - QSqlQuery::value: not positioned on a valid record
hein? 23 10:54:32 Jolla [3732]: [D] Car::lifetime:1412 - Find lifetime in database: 0 
hein? 23 10:54:32 Jolla [3732]: [D] Car::lifetime:1416 - Default lifetime not set in database, set to 0 
hein? 23 10:54:32 Jolla [3732]: [W] QSqlQuery::value:416 - QSqlQuery::value: not positioned on a valid record
hein? 23 10:54:32 Jolla [3732]: [D] Car::distanceunity:1250 - Find distanceunity in database: "" 
hein? 23 10:54:32 Jolla [3732]: [D] Car::distanceunity:1254 - Default distanceunity not set in database, set to Km 
hein? 23 10:54:32 Jolla [3732]: [D] Car::budget_invest:727 - Invalid buying date 
hein? 23 10:54:32 Jolla [3732]: [D] Car::budget_invest:729 - 0 
hein? 23 10:54:32 Jolla [3732]: [W] QSqlQuery::value:416 - QSqlQuery::value: not positioned on a valid record
hein? 23 10:54:32 Jolla [3732]: [D] Car::currency:1209 - Find currency in database: "" 
hein? 23 10:54:32 Jolla [3732]: [74B blob data]
hein? 23 10:54:32 Jolla kernel: harbour-carbudg: unhandled page fault (11) at 0x00000018, code 0x005
hein? 23 10:54:32 Jolla kernel: pgd = d6ec8000
hein? 23 10:54:32 Jolla kernel: [00000018] _pgd=00000000
hein? 23 10:54:32 Jolla kernel: hein? 23 10:54:32 Jolla kernel: Pid: 3732, comm: harbour-carbudg
hein? 23 10:54:32 Jolla kernel: CPU: 0 Tainted: P W O (3.4.106.20150416.1 #1)
hein? 23 10:54:32 Jolla kernel: PC is at 0x4234e154
hein? 23 10:54:32 Jolla kernel: LR is at 0x4150e59f
hein? 23 10:54:32 Jolla kernel: pc : [<4234e154>] lr : [<4150e59f>] psr: 200f0010
sp : be9fb058 ip : 41578358 fp : 00000613
hein? 23 10:54:32 Jolla kernel: r10: 0000041e r9 : 40de29f0 r8 : 4e368008
hein? 23 10:54:32 Jolla kernel: r7 : 4e488c80 r6 : 4e488c80 r5 : 4e368100 r4 : 41576e50
hein? 23 10:54:32 Jolla kernel: r3 : 00000018 r2 : 4e2b5ce0 r1 : 4e368100 r0 : 4e368100
hein? 23 10:54:32 Jolla kernel: Flags: nzCv IRQs on FIQs on Mode USER_32 ISA ARM Segment user
hein? 23 10:54:32 Jolla kernel: Control: 10c5787d Table: 970c806a DAC: 00000015
hein? 23 10:54:32 Jolla kernel: [<c010b930>](unwind_backtrace+0x0/0x11c) from [<c010f860>](__do_user_fault+0x7c/0xc4)
hein? 23 10:54:32 Jolla kernel: [<c010f860>](__do_user_fault+0x7c/0xc4) from [<c08ae268>](do_page_fault+0x374/0x3c0)
hein? 23 10:54:32 Jolla kernel: [<c08ae268>](do_page_fault+0x374/0x3c0) from [<c01002d4>](do_DataAbort+0x134/0x1a8)
hein? 23 10:54:32 Jolla kernel: [<c01002d4>](do_DataAbort+0x134/0x1a8) from [<c08aca94>](__dabt_usr+0x34/0x40)
hein? 23 10:54:32 Jolla kernel: Exception stack(0xdd26dfb0 to 0xdd26dff8)
hein? 23 10:54:32 Jolla kernel: dfa0: 4e368100 4e368100 4e2b5ce0 00000018
hein? 23 10:54:32 Jolla kernel: dfc0: 41576e50 4e368100 4e488c80 4e488c80 4e368008 40de29f0 0000041e 00000613
hein? 23 10:54:32 Jolla kernel: dfe0: 41578358 be9fb058 4150e59f 4234e154 200f0010 ffffffff
hein? 23 10:54:32 Jolla kernel: harbour-carbudg(3732) send signal 11 to harbour-carbudg(3732)
hein? 23 10:54:32 Jolla mapplauncherd[1005]: Boosted process (pid=3732) was terminated due to signal 11
hein? 23 10:54:32 Jolla invoker[3980]: error: Can't send signal 11 to application [3732]: No such process
hein? 23 10:54:32 Jolla kernel: booster-silica-(1005) send signal 11 to invoker(3980)
hein? 23 10:54:32 Jolla kernel: invoker(3980) send signal 11 to invoker(3980)
hein? 23 10:55:22 Jolla lipstick[844]: [W] unknown:22 - file:///usr/share/lipstick-jolla-home-qt5/compositor/GlassBackground.qml:22:5: QML Image: Cannot open: file:image:/theme/graphic-wallpaper-application
hein? 23 10:55:22 Jolla lipstick[844]: [W] unknown:293 - file:///usr/share/lipstick-jolla-home-qt5/switcher/Switcher.qml:293:35: Unable to assign [undefined] to QQmlComponent_

**Comment by condo4** [comment]
I can't reproduce anymore... close it (will be re-open if appear another time)

**Comment by direc85** [comment]
This was related most likely with database handling operations, e.g. selecting another car or re-selecting the same car. I have refined database handling a lot, so I think this has been actually fixed.
