### ISSUE TITLE
comsumption and last = 0

### ISSUE THREAD

**Issue by paolomi** [condo4/carbudget#38]
Hi :)

Add a new car, then add 2 tanks:
1-
odo 150000
quantity 20
price 30
full tank: no

2-
odo 150100
quantity 20
price 25
full tank: no

Now restart the app and you'll see:
Consumption: 0.00l/100Km
Last: 0.00l/100Km

something is wrong: consumption and last should not be zero.

then in budget, you'll see:
Costs per 100Km
fuel 25€
I think it should be 30€, the cost of the first tank, because we have not consumed the fuel of the second tank...  however, the most important bug is comsumption and last = 0

**Comment by condo4** [comment]
hello,
This is not a bug, in fact it is impossible to calculate a consumption since you don't have 2 full tank.
The reason is, when you add a "not full" tank, we can't know the old level of your tank.

The only way to calculate consumsion with exactitude, is to allways do full tank.
