### ISSUE TITLE
small language inconsistencies

### ISSUE THREAD

**Issue by fferner** [condo4/carbudget#43]
While reviewing some of the German translation, I came across a few (minor) language inconsistencies/oddities...

I'm mainly recording this here and let you know that I'm planning to go over the ones I spot and fix them in the next few days. Unfortunately I guess that means more issues for translators to other languages but hopefully not too much... Hopefully most pull request will follow later today or tomorrow.

One example was the use of "description" vs "note" for what I believe is the same field for a tank entry in TankEntry.qml and TankEntryView.qml.

**Comment by direc85** [comment]
Hi,

You are correct, there are some inconsistencies. I can try to unify the terninology used monday evening. Could you wait until then?

And yes, the "note" and "description" refer to the same data field - which in my mind is a note / additional information, even a comment field.

**Comment by fferner** [comment]
I've just pushed the first I noticed but I'm happy to wait with further updates until you've done your updates. (I've not immediately spotted anything else but haven't checked too closely.) Let me know when you think I should have another look.
