### ISSUE TITLE
Publish updates to Jolla store

### ISSUE THREAD

**Issue by direc85** [condo4/carbudget#57]
Hi. It has been a while now, and I haven't had any issues with most recent builds. Could you push the changes to Jolla store so others can benefit from them, too? Thanks!

**Comment by condo4** [comment]
Hi,
I try to published it  this morning, but, there was some check issue; I will open some issues and will try to fixed it this week if I find time to work on this project.

**Comment by condo4** [comment]
Version Tagged 0.20 was send to harbour for validation...
There was no more warnings in QA tool.
