### ISSUE TITLE
Missing aarch64 (and i486) builds

### ISSUE THREAD

**Issue by direc85** [condo4/carbudget#65]
Hi,

There is no aarch64 build available in OpenRepos. I compiled it for me and it works without modifications so it should be a simple recompile.

If you are not willing to maintain the application any more, I can continue providing new builds both in Jolla Store and OpenRepos.

Thanks!

**Comment by pagism** [comment]
I was thinking about the same, it's a really good app and can be improved even more, but firstly the aarch64 build is needed, thanks

**Comment by condo4** [comment]
Hi,
I will generate a new release (with aarch64) in few days...
I have to re-install fully SDKs.

**Comment by direc85** [comment]
I made a PR #66 which fixes many crashes and assumptions in the code. I suggest you use that instead.

I can also provide you the .rpm packages, if you have trouble getting it up to speed. Just make a version bump of your choice and ping me :grin:

**Comment by condo4** [comment]
Now, version 0.21 is sent for i486, aarch64 and armv7hl on OpenRepos and Jolla Store (waiting for validation)
