### ISSUE TITLE
Local decimal separator issue

### ISSUE THREAD

**Issue by mrjoops** [condo4/carbudget#72]
Hi,

In my country, the default decimal separator is the comma (,) while it is the dot (.) in english.

When I enter a value, the comma is accepted, as expected, but once saved the dot is displayed instead. It wouldn't be much of an issue if the dot wasn't kept in the the input field on edit, causing a field validation error.

Thank you again for your work!

**Comment by direc85** [comment]
This was fixed in #70 but it has not been released in an update yet.

**Comment by mrjoops** [comment]
Indeed! Sorry for the duplicate then, I was on a ticket opening spree ;) and while I checked for the previous one, I missed to check this one!
